### ISSUE TITLE
Parse command line arguments for user input

### ISSUE THREAD

**Issue by vladimirkovacevic** [katarinaetfpos/Burrows_Wheeler_FM_index#1]
In order to enable usage of bioinformatic tools in the workflow its inputs need to be received through command line arguments. I suggest usage of docopt library. Very neat interface, allows default values. Here is an [example](https://github.com/sbg/smart-variant-filtering/blob/master/svf_apply.py).
No need to have selection of optimized/non optimized, it can be concluded by factors provided for downsampling of suffix array and tally, if both are 1 then it's non-optimized.
Also provide input for patterns and text. These ones given in the assignment could be default values.

**Comment by katarinaetfpos** [comment]
Provided input of patterns and factors through command line.
